# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

extends:
  template: .pipelines/M365GovernedTemplates/M365.NonOfficial.Release.yml@Test
  parameters:
    platform:
      name: m365
      workload: 'SPO'
      serviceTreeId: "28a2529f-7085-4bbf-aa02-787135bb26a8"
      serviceGroupName: 'cosmic.saferolloutconfig.services'
      sdpPolicyInput:
        payloadName: "OceLocatorJobs"
    stages:
    - stage: 'Prod_RolloutServiceSetup'
      displayName: 'RolloutServiceSetup'
      variables:
        stage_type: nonDeployment
        useV2BedrockTask: true
      jobs:
      - job: 'RegisterPayload'
        pool: 
          type: release
        steps:
        - task: saferolloutfc.SafeRolloutExtension.RolloutServiceAgent.RolloutServiceAgent@2
          inputs:
            Command: 'register'
            PayloadType: 'SPOF'
            PayloadScope: 'SPOF'
            PayloadRisk: 'Medium'
            PayloadNameregister: "OceLocatorJobs"
            PayloadMetaData: "{'$type': 'EV2Rollout', 'Environment': 'global' }"
