# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

extends:
  template: v2/Microsoft.NonOfficial.yml@OneBranchTemplates
  parameters:
    platform:
      name: m365
      workload: 'SPO'
      serviceTreeId: $(service_tree_id)
      serviceGroupName: 'cosmic.saferolloutconfig.services'
      sdpPolicyInput:
        payloadName: <ServiceName>
    stages:
    - stage: 'Prod_RolloutServiceSetup'
      displayName: 'RolloutServiceSetup'
      variables:
        stage_type: nonDeployment
        useV2BedrockTask: true
      jobs:
      - job: 'RegisterPayload'
        pool: 
          type: release
        steps:
        - task: saferolloutfc.SafeRolloutExtension.RolloutServiceAgent.RolloutServiceAgent@2
          inputs:
            Command: 'register'
            PayloadType: 'SPOF'
            PayloadScope: 'SPOF'
            PayloadRisk: 'Medium'
            PayloadNameregister: <ServiceName>
            PayloadMetaData: "{'$type': 'EV2Rollout', 'Environment': 'global','RolloutSpecName':'<EV2serviceGroupName>' }"
