parameters:
- name: stage
  type: stage  

- name: featureFlags
  type: object
  default: {}

- name: platform
  type: object

stages:

- ${{if eq(parameters.platform.name, 'onebranch') }} :
    template: OneBranch/OneBranch.Release.Prod.Stage.yml  
    parameters:
      stage: ${{parameters.stage}}
      featureFlags: ${{parameters.featureFlags}}
  
  ${{ elseif eq(parameters.platform.name, 'm365') }}:
    template: M365/Release.NonProd.Stage.yml
    parameters:
      stage: ${{parameters.stage}}
      serviceTreeId: ${{parameters.platform.serviceTreeId}}

  ${{ elseif eq(parameters.platform.name, 'm365conductor') }} :
    template: M365/M365Conductor.Release.Stage.yml  
    parameters:
      stage: ${{parameters.stage}}