trigger: none
    
resources:
  repositories:
  - repository: GovernedTemplates
    type: git
    name: OneBranch.Pipelines/GovernedTemplates
    ref: refs/heads/main

  pipelines:
  - pipeline: PrimaryArtifact
    source: "ControlPlane Official"
    branch: master

extends:
  template: v2/Microsoft.Official.yml@GovernedTemplates
  parameters:
    platform:
      name: m365
      workload: Substrate
      serviceTreeId: '28a2529f-7085-4bbf-aa02-787135bb26a8'
      serviceGroupName: "GriffinEv2Samples"
    featureFlags: 
      enableCheckout: true
    stages:
      - stage: 'Gal_GriffinAzureEv2Sample'
        variables:
          stage_type: deployment
          azure_subscription_id: "b2258e9e-2f02-4442-bbe5-94d583e64e75"
        jobs:
          - job: ReleaseJob
            pool:
              type: release
            steps:
              - download: PrimaryArtifact
              - task: artifactDropDownloadTask@0
                inputs:
                  dropMetadataContainerName: DropMetaData
                  rootPaths: '/target/Distrib/GriffinComponents/all/retail/amd64/GriffinAzureEv2/GriffinEv2Sample/'
                  usePat: false
              - task: prepare-deployment@1
                env:
                  ServiceTreeId: '28a2529f-7085-4bbf-aa02-787135bb26a8'
                  ServiceGroupName: "GriffinEv2Samples"
                inputs:
                  taskType: 'setupLockboxAuthzVariables'
              - task: ExpressV2Internal@1
                inputs:
                  EndpointProviderType: 'LockboxService'
                  ServiceRootPath: '$(System.DefaultWorkingDirectory)/drop/target/Distrib/GriffinComponents/all/retail/amd64/GriffinAzureEv2/GriffinEv2Sample/'
                  RolloutSpecPath: '$(System.DefaultWorkingDirectory)/drop/target/Distrib/GriffinComponents/all/retail/amd64/GriffinAzureEv2/GriffinEv2Sample/RolloutSpec.GallatinTorus.json'