parameters:
  - name: azureSubscriptionId
    type: string  

  - name: serviceTreeId
    type: string

  - name: serviceGroupName
    type: string
  
  - name: workload
    type: string

  - name: cloudName
    type: string

  - name: releaseEnvironment
    type: string
  
  - name: ev2Environment
    type: string

  - name: phase
    type: string

  - name: serviceType
    type: string

  - name: stageType
    type: string

  - name: job
    type: job  

jobs:

- job: ${{ parameters.job.job }}
  ${{ if ne(parameters.job.displayName, '') }}:
    displayName: ${{ parameters.job.displayName }}  
  ${{ if ne(parameters.job.condition, '') }}:
    condition: ${{ parameters.job.condition }}
  ${{ if ne(parameters.job.continueOnError, '') }}:
    continueOnError: ${{ parameters.job.continueOnError }}
  ${{ if ne(parameters.job.timeoutInMinutes, '') }}:
    timeoutInMinutes: ${{ parameters.job.timeoutInMinutes }}
  ${{ if ne(parameters.job.cancelTimeoutInMinutes, '') }}:
    cancelTimeoutInMinutes: ${{ parameters.job.cancelTimeoutInMinutes }}
  ${{ if eq(parameters.job.pool, 'server') }}:
    pool: ${{ parameters.job.pool }}
  ${{ if not(eq(parameters.job.pool, 'server')) }}:
    pool:
      name: OneBranchPipelines 
      # ${{ if eq(parameters.cloudName, 'Public') }}:
      #   agentPooltype: "M365ComplianceProd"
      agentPooltype: "M365ComplianceProd"
  dependsOn: 
    - ${{ if eq(parameters.stageType, 'deployment') }}:
#We will add dependency only in case of deployment stages for the Lockbox approval flow
      - WaitForLockBoxApproval
      - LockBoxApprovalReq
    - ${{ each dep in parameters.job.dependsOn }}:
      - ${{ dep }}
  variables:
  - ${{ if ne(parameters.job.variables, '') }}:
    - ${{ each v in parameters.job.variables }}:
      - ${{ if ne(v.key, '') }}:
        - name: ${{ v.key }}
          value: ${{ v.value }}
      - ${{ else }}:
        - ${{ insert }}: ${{ v }}
  - ${{ if eq(parameters.stageType, 'deployment') }}:
    - name: LockboxRequestId
      value: $[ dependencies.LockBoxApprovalReq.outputs['LbApprovalRequestTask.lockboxRequestId'] ]
 
  steps:
  - template: ../../Steps/M365/Release.NonProd.Step.yml
    parameters:
      steps: ${{ parameters.job.steps }}
      serviceTreeId: ${{parameters.serviceTreeId}}
      serviceGroupName: ${{parameters.serviceGroupName}}
      workload: ${{parameters.workload}}
      cloudName: ${{parameters.cloudName}}
      releaseEnvironment: ${{parameters.releaseEnvironment}}
      ev2Environment: ${{parameters.ev2Environment}}
      phase: ${{parameters.phase}}
      serviceType: ${{parameters.serviceType}}
      stageType: ${{parameters.stageType}}
      azureSubscriptionId: ${{parameters.azureSubscriptionId}}
      

  